# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-21 11:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ('date_created',)},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(blank=True, max_length=1500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='site',
            field=models.URLField(blank=True, verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='stars',
            field=models.IntegerField(blank=True, default=0, editable=False, verbose_name='stars'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
    ]
