# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-21 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_auto_20171021_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='category',
            field=models.CharField(choices=[('HOT', 'Hotel'), ('PEN', 'Pensiune'), ('HOS', 'Hostel'), ('APA', 'Apartament'), ('VIL', 'Vila'), ('CAB', 'Cabana'), ('GAR', 'Garsoniera')], default=('HOT', 'Hotel'), max_length=20, verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descriere'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Titlu'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='site',
            field=models.URLField(blank=True, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='stars',
            field=models.IntegerField(blank=True, default=0, editable=False, verbose_name='Voturi'),
        ),
    ]
