# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-21 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_auto_20171021_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(choices=[('HOT', 'Hotel'), ('PEN', 'Pensiune'), ('HOS', 'Hostel'), ('APA', 'Apartament'), ('VIL', 'Vila'), ('CAB', 'Cabana'), ('GAR', 'Garsoniera')], default=('HOT', 'Hotel'), help_text='Tipul anuntului', max_length=3, verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(blank=True, help_text='Descriere amanuntita a anuntului', max_length=1500, verbose_name='Descriere'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='mail',
            field=models.EmailField(blank=True, help_text='Adresa de email', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='name',
            field=models.CharField(help_text='Titlul anuntului - nu se accepta nume nule (goale)', max_length=100, verbose_name='Titlu'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='phone',
            field=models.CharField(blank=True, help_text='Numarul de telefon', max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='site',
            field=models.URLField(blank=True, help_text='Adresa web a proprietatii', verbose_name='Site'),
        ),
    ]
