# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-21 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_auto_20171021_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='price',
            field=models.IntegerField(default=0, help_text='Pretul in euro', verbose_name='Pret'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(choices=[('HOT', 'Hotel'), ('PEN', 'Pensiune'), ('HOS', 'Hostel'), ('APA', 'Apartament'), ('VIL', 'Vila'), ('CAB', 'Cabana'), ('GAR', 'Garsoniera'), ('BIR', 'Birou'), ('SPA', 'Spatiu comercial'), ('ALT', 'Altceva')], default=('HOT', 'Hotel'), help_text='Tipul anuntului', max_length=3, verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='name',
            field=models.CharField(help_text='Titlul anuntului <br>Titlul anuntului este primul lucru observat de client. <br>Acesta ar trebui sa contina informatii concrete si atragatare.<br>Nu se accepta nume nule (goale)!<br>Nu puteti avea mai multe anunturi cu acelasi nume!', max_length=100, verbose_name='Titlu'),
        ),
    ]
