# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-21 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Booking', '0007_auto_20171021_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterUniqueTogether(
            name='advertisement',
            unique_together=set([('user', 'name')]),
        ),
    ]
