# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-21 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0008_auto_20171021_2141'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='advertisement',
            unique_together=set([]),
        ),
    ]
