# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-21 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0009_auto_20171021_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='wifi',
            field=models.BooleanField(default=False, help_text='Specificati daca exista serviciul wi-fi', verbose_name='Wi-Fi'),
        ),
    ]
