# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-21 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0010_advertisement_wifi'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='children_playground',
            field=models.BooleanField(default=False, verbose_name='Loc de joaca pentru copii'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='launch',
            field=models.BooleanField(default=False, verbose_name='Mic dejun'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='Parcare'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='spa',
            field=models.BooleanField(default=False, verbose_name='SPA'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='swimming_pool',
            field=models.BooleanField(default=False, verbose_name='Piscina'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(choices=[('HOT', 'Hotel'), ('PEN', 'Pensiune'), ('HOS', 'Hostel'), ('APA', 'Apartament'), ('VIL', 'Vila'), ('CAB', 'Cabana'), ('GAR', 'Garsoniera'), ('BIR', 'Birou'), ('SPA', 'Spatiu comercial'), ('ALT', 'Altceva')], default=('HOT', 'Hotel'), help_text='Tipul anuntului<br><br><h3>Servicii oferite</h3>', max_length=3, verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='wifi',
            field=models.BooleanField(default=False, verbose_name='Wi-Fi'),
        ),
    ]
