# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-22 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0011_auto_20171021_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='phone',
            field=models.CharField(help_text='Numarul de telefon', max_length=20, verbose_name='Telefon'),
        ),
    ]
