# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-22 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0012_auto_20171022_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='city',
            field=models.CharField(default='oras', max_length=100, verbose_name='Localitate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='county',
            field=models.CharField(choices=[('AB', 'Alba'), ('AG', 'Arges'), ('AR', 'Arad'), ('B', 'Bucuresti'), ('BC', 'Bacau'), ('BH', 'Bihor'), ('BN', 'Bistrita-Nasaud'), ('BR', 'Braila'), ('BT', 'Botosani'), ('BV', 'Brasov'), ('BZ', 'Buzau'), ('CJ', 'Cluj'), ('CL', 'Calarasi'), ('CS', 'Caras-Severin'), ('CT', 'Constanta'), ('CV', 'Covasna'), ('DB', 'Dambovita'), ('DJ', 'Dolj'), ('GJ', 'Gorj'), ('GL', 'Galati'), ('GR', 'Giurgiu'), ('HD', 'Hunedoara'), ('HR', 'Harghita'), ('IF', 'Ilfov'), ('IL', 'Ialomita'), ('IS', 'Iasi'), ('MH', 'Mehedinti'), ('MM', 'Maramures'), ('MS', 'Mures'), ('NT', 'Neamt'), ('OT', 'Olt'), ('PH', 'Prahova'), ('SB', 'Sibiu'), ('SJ', 'Salaj'), ('SM', 'Satu Mare'), ('SV', 'Suceava'), ('TL', 'Tulcea'), ('TM', 'Timis'), ('TR', 'Teleorman'), ('VL', 'Valcea'), ('VN', 'Vrancea'), ('VS', 'Vaslui')], default=('AB', 'Alba'), max_length=2, verbose_name='Judet'),
        ),
    ]
