# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-22 16:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0013_auto_20171022_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='stars',
            field=models.IntegerField(blank=True, default=1, editable=False, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Stele'),
        ),
    ]
