# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-22 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0015_auto_20171022_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image_0',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profiles/%Y/%m/%d', verbose_name='Imaginea de galerie 1'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image_1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profiles/%Y/%m/%d', verbose_name='Imaginea de galerie 2'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image_2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profiles/%Y/%m/%d', verbose_name='Imaginea de galerie 3'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image_3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profiles/%Y/%m/%d', verbose_name='Imaginea de galerie 4'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image_4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='galery/%Y/%m/%d', verbose_name='Imaginea de galerie 5'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='name',
            field=models.CharField(help_text='Titlul anuntului <br>Titlul anuntului este primul lucru observat de client. <br>Acesta ar trebui sa contina informatii concrete si atragatare.<br>Nu se accepta nume nule (goale)!', max_length=100, verbose_name='Titlu'),
        ),
    ]
