# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-27 17:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0016_auto_20171022_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(choices=[('HOT', 'Hotel'), ('PEN', 'Pensiune'), ('HOS', 'Hostel'), ('APA', 'Apartament'), ('VIL', 'Vila'), ('CAB', 'Cabana'), ('GAR', 'Garsoniera'), ('BIR', 'Birou'), ('SPA', 'Spatiu comercial'), ('ALT', 'Altceva')], default=('HOT', 'Hotel'), help_text='Tipul anuntului', max_length=3, verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='main_image',
            field=models.ImageField(blank=True, default=None, help_text='Imaginea de prezentare<br><br><br>Galerie foto', null=True, upload_to='profiles/%Y/%m/%d', verbose_name='Imaginea de profil'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='stars',
            field=models.IntegerField(default=0, help_text='Daca acest argument nu se aplica anuntului dumneavoastra, utilizati valoarea 0<br><br><h3>Servicii oferite</h3>', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Stele'),
        ),
    ]
