# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-27 17:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0017_auto_20171027_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='stars',
            field=models.IntegerField(default=0, help_text='Daca acest argument nu se aplica anuntului dumneavoastra, utilizati valoarea 0!<br><br><h3>Servicii oferite</h3>', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Stele'),
        ),
    ]
